### ISSUE TITLE
Allow room size and availability data input

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#10]
Epic: #2 

### Description
As a user, I want to be able to input data defining available rooms and maximum capacity for each room.

### Tasks

- [ ]  Add functionality to add/delete rows
- [ ]  Implement input validation
- [ ]  Implement form validation before continuing to the next section
