### ISSUE TITLE
Allow period time data input

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#11]
Epic: #2 

### Description
As a user, I want to input period times for scheduling purposes.

### Tasks

- [x] Add functionality to add/delete rows
- [x] Implement input validation
- [x] Implement form validation before continuing to the next section

**Comment by salsajeries** [comment]
Closing issue
