### ISSUE TITLE
UI: Data input page

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#26]
Epic: #4 

### Description
As a user, I want the option of being able to input data through a graphical interface or through uploading a file.

### Dependencies
#37 - Mirror this input format on UI

### Tasks

- [x] Mirror input file on frontend design
- [x] Design page mockup in Figma
- [x] Implement design on frontend

**Comment by salsajeries** [comment]
Included in #41
