### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by David-T-Projects** [BSSD-Technologies/ChargerSync#31]
Epic: #2 

### Tasks

- [x] Install DB into Docker Container
- [x] Link DB into code
- [x] Design schema for DB
- [x] Perform acceptance testing

**Comment by salsajeries** [comment]
This is done now
