### ISSUE TITLE
Design Generation Algorithm

### ISSUE THREAD

**Issue by David-T-Projects** [BSSD-Technologies/ChargerSync#32]
Epic: #3 

### Description

Design the generation algorithm and perform proof of concept work

### Tasks

- [ ] Design the algorithm
- [ ] Create a document detailing the design
- [ ] Perform proof of concept testing

**Comment by salsajeries** [comment]
Marking as done bc we think it is
