### ISSUE TITLE
Test Data Input/Management Module

### ISSUE THREAD

**Issue by David-T-Projects** [BSSD-Technologies/ChargerSync#34]
Epic: #33 

### Description

Perform full scale testing on the Data Input/Management Module

### Tasks

- [ ] Perform integration testing with existing code base
- [ ] Ensure adequate unit testing coverage
- [ ] Perform full-scale test of entire module
