### ISSUE TITLE
Test Schedule/Conflict Generation Module

### ISSUE THREAD

**Issue by David-T-Projects** [BSSD-Technologies/ChargerSync#35]
Epic: #33 

### Description

Perform full scale testing on the Schedule/Conflict Generation module

### Tasks

- [ ] Perform integration testing with existing code base
- [ ] Ensure adequate unit testing coverage
- [ ] Perform full-scale test of entire module
