### ISSUE TITLE
Test User Interface Module

### ISSUE THREAD

**Issue by David-T-Projects** [BSSD-Technologies/ChargerSync#36]
Epic: 

### Description

Perform full scale testing on the User Interface module

### Tasks

- [ ] Perform integration testing with existing code base
- [ ] Ensure adequate unit testing coverage
- [ ] Perform full-scale test of entire module
