### ISSUE TITLE
Download Manually Input Responses

### ISSUE THREAD

**Issue by David-T-Projects** [BSSD-Technologies/ChargerSync#40]
Epic: #2 

### Description

Implement support for downloading user responses

### Tasks

- [x] Convert all zustand global stores to JSON on frontend
- [x] Convert JSON->CSV
- [x] Start download of file

**Comment by salsajeries** [comment]
Closed with #39
