### ISSUE TITLE
Implement /import/courses endpoint

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#46]
Epic: #45 

### Description
As a user, I want to be able to send an uploaded course list template as .csv to the backend for processing.

### Tasks

- [ ] Create endpoint in app.py
- [ ] Verify parameter can be received properly
- [ ] Verify output can be sent properly
- [ ] Define status codes

**Comment by salsajeries** [comment]
Branch merged
