### ISSUE TITLE
Implement /import/instructors endpoint

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#49]
Epic: #45 

### Description
As a user, I want to be able to send an uploaded instructor list template as .csv to the backend for processing.

### Tasks

- [x] Create endpoint in app.py
- [x] Verify parameter can be received properly
- [x] Verify output can be sent properly
- [x] Define status codes
