### ISSUE TITLE
Implement /generate/schedule

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#50]
Epic: #45 

### Description
As a user, I want to send all my inputted data to the backend to be processed and turned into a schedule, then receive the generated schedule.

### Tasks

- [x] Create endpoint in app.py
- [x] Verify parameter can be received properly
- [ ] Verify output can be sent properly
- [ ] Define status codes
