### ISSUE TITLE
Allow instructor data input

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#51]
Epic: #2 

### Description
As a user, I want to be able to input data about instructors to be assigned to courses.

### Tasks

- [x] Add functionality to add/delete rows
- [x] Implement input validation
- [x] Implement form validation before continuing to the next section

**Comment by salsajeries** [comment]
branch merged
