### ISSUE TITLE
Allow instructor preference data input

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#52]
Epic: #2 

### Description
As a user, I want to be given the option to input data regarding instructor preferences.

### Tasks

- [ ] Automatically populate accordion with instructor list
- [ ] Automatically populate course preference options with course list
- [ ] Automatically populate time period preference with period list
- [ ] Implement input validation for preferences
