### ISSUE TITLE
Implement /export/schedule endpoint

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#68]
Epic: #45 

### Description
As a user, I want to be able to export the generated schedule with any desired filters as a .csv

### Tasks

- [ ] Create endpoint in app.py
- [ ] Verify parameter can be received properly
- [ ] Verify output can be sent properly
- [ ] Define status codes
