### ISSUE TITLE
Define input data types

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#8]
Epic: #2 

### Description
As a user, I want to be able to input data from faculty members about what time, classes, and rooms they would like to teach.

### Tasks

- [x] Define "Course" type
- [x] Define "Room" type
- [x] Define "Period" type
- [x] Define "Instructor" type
- [x] Define "Course Preference" type
- [x] Define "Period Preference" type
