### ISSUE TITLE
UI: Display conflicts and incompletes

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#83]
Epic: #4 

### Description
As a user, I want to be able to view conflicts and incompletes in the designed format.

### Tasks

- [ ] Create accordion of courses
- [ ] Create table for each course
- [x] Define table column headers
