### ISSUE TITLE
Allow course and enrollment data input

### ISSUE THREAD

**Issue by salsajeries** [BSSD-Technologies/ChargerSync#9]
Epic: #2 

### Description
As a user, I want to be able to input data about courses to be offered and preliminary enrollments if available.

### Tasks

- [ ] Add functionality to add/delete rows
- [ ] Implement input validation
- [ ] Implement form validation before continuing to the next section
